apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-webchat-config
data:
  PYTHONPATH: app
  MONGO_DB_CONNECTION_URI: mongodb://mongodb:27017
  MONGO_DB_ADMIN_USERNAME: admin
  MONGO_DB_ADMIN_PASSWORD: admin
  KAFKA_URL: chat-kafka:29092

