version: '3'

services:
  main-app:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    container_name: chat-app
    ports:
      - "${API_PORT}:8000"
    command: "uvicorn --factory src.api.main:create_app --timeout-graceful-shutdown 2 --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - webchat-kafka

networks:
  backend:
    driver: bridge
