version: '3'

services:
  main-app:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    container_name: chat-app
    ports:
      - "${API_PORT}:8000"
    command: "uvicorn --factory src.api.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge
